import Head from 'next/head';
import { useRouter } from 'next/router'

const Dynamic = () => {
  const router = useRouter();
  const query = router.query
  console.log("query", query);
  return (
    <div>
      <Head>
        <title>{router.query.dyn}</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      Hi there, I am a dynamic route: {router.query.dyn}
    </div>
  );
};

export default Dynamic;